# Generated by Django 2.0.6 on 2020-03-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('miaoshu', models.TextField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('lunbo_pic', models.ImageField(upload_to='lunbo_pics')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
