# Generated by Django 2.0.6 on 2020-03-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zhangjie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.FileField(upload_to='zhangjie_pics')),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('album_id', models.CharField(blank=True, max_length=36, null=True)),
                ('audio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'zhangjie',
            },
        ),
        migrations.CreateModel(
            name='Zhuanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('boyin', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('brief', models.CharField(blank=True, max_length=255, null=True)),
                ('fabu_date', models.DateField(blank=True, null=True)),
                ('album_pic', models.ImageField(upload_to='album_pic')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('shangchuan_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zhuanji',
            },
        ),
    ]
