# Generated by Django 2.0.6 on 2020-03-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('header_pic', models.ImageField(upload_to='header_pics')),
                ('faming', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('qianming', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('zhuce_time', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
